### ISSUE TITLE
adapt sample to oidc-client-ts

### ISSUE THREAD

**Issue by pamapa** [authts/sample-angular-oidc-client-ts#1]
- [ ] in typescript code
- [ ] replace html code (signin-callback.html + silent-callback.html) with routing and typescript modules

**Comment by jeffschulzusc** [comment]
@pamapa can you add me to collaboarate and create fix-1 branch

**Comment by jeffschulzusc** [comment]
i have the upgrades done/staged ... waiting for write access, fix-1 branch ... also:
need to: 
publish oidc-client-ts.js/oidc-client-ts.min.js to https://cdnjs.com/libraries from authts/oidc-client-ts github action, with integrity hash

**Comment by pamapa** [comment]
The idea is to use instead of signin-callback.html  with `<script src="https://cdnjs.cloudflare.com/ajax/libs/oidc-client/1.7.0/oidc-client.js"></script>` angular routing support. The main angular application shall take over the redirects...

cdnjs makes sense for none javascript framework based application (none SPA) and when we have 2.0.0.

Please replace that code in the sample with angular routing.

**Comment by pamapa** [comment]
i have now requested https://cdnjs.com support via issue...

**Comment by pamapa** [comment]
> 
> 
> @pamapa can you add me to collaboarate and create fix-1 branch

please fork this project, create a branch and create a pull request on this project

**Comment by jeffschulzusc** [comment]
fix-1 is in place ... see https://github.com/jeffschulzusc/sample-angular-oidc-client-ts/commits/fix-1 ...
**but need:**
**A.** when oidc-client-ts is hosted on cdnjs, i will update silent-callback.html
**B.** oidc-client seemed to loadUserInfo, oidc-client-ts does not ... is there a difference in ResponseValidator ?
   OidcSettings/Store seems to have same defaults ... see below about 'opinionated'

CHANGES:

1. environment.prod.ts had clientId: 'implicit' ... but this is not an advertised client on the demo identity server 4 ...
   and anyways we would want to discourage implicit flow ... https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-04.txt
   so i set to clientId: 'interactive.public' same as environment.ts

2. uninstall oidc-client, install oidc-client-ts ...
   auth.service.ts: import from oidc-client-ts

NOTE: after switching to oidc-client-ts, on renewToken->signinSilent [ResponseValidator] _processClaims: not loading user info, 
      so username,email etc is not brought into the user that is returned in the promise

3. new app-routing.module.ts, remove assets/signin-callback.html, and
   in auth.service.ts: redirect_uri: `${environment.clientRoot}signin-callback`,
   in app.component.ts: public refresh() called from SigninCallback guard 
   
NOTE: AppComponent.refresh() is hacky ... prefer to have ui in a HomeComponent and app.component have <router-outlet>

4. move silent-callback.html out of assets and into src, load oidc-client-ts, and
   add to angular.json build-options-assets so that is put in root of build 
   (because, do not want to load the whole angular site in iframe)
   auth.service.ts: silent_redirect_uri: `${environment.clientRoot}silent-callback.html`,

NOTE: temporarily hosted at https://jeffschulzusc.github.io/oidc-client-ts.js until it is available on cdnjs


Q. What is intention of !! here:
  this.filterProtocolClaims = !!filterProtocolClaims;
  this.loadUserInfo = !!loadUserInfo;


SUGGEST:
- make auth.service oidc UserManagerSettings 'opinionated' ? ie:
  response_mode: 'query',
  loadUserInfo: true,
- put in a flag/debounce or other so that auth.service renewToken isnt called while there is current renew active ?
- compilerOptions,angularCompilerOptions to strictest settings
- clean build, no compiler/lint warnings
- <router-outlet> and move ui to a HomeComponent
- if we opinionate the UserManager to response_mode: 'query', then silent-callback.html could probably just post message itself
  ex. window.parent.postMessge( location.href,location.origin ) and IFrameWindow would get it (or some browsers might not allow?)

**Comment by pamapa** [comment]
The sample shall use the default settings:
- filterProtocolClaims is true by default
- loadUserInfo  is false by default
- ...

you most probably only need to configure authority, client_id and redirect_uri. 

silent-callback.html should be replace with typescript routing code

there should be one central place to hold the odic configuration (probably environment depended) and the used for all oidc related stuff...

**Comment by jeffschulzusc** [comment]
"silent-callback.html should be replace with typescript routing code" ... see above, this exists in root ... because do not want to load the whole angular site in an iframe within the angular site

**Comment by jeffschulzusc** [comment]
i see oidc-client-ts is at cdnjs, but can not resolve to a .js that works ... expecting that just oidc-client-ts.js (or minified version) would be there ...
so, i used angular glob to build the oidc-client-ts.js from node_modules into the root of the angular site ...
then silent-callback.html script src="./oidc-client-ts.js" ...
this way, there is no chance for version discrepancy
commit 8e1a9c8

**Comment by pamapa** [comment]
@jeffschulzusc I am ok with the angular glob, can you fork, create a branch, commit and submit a merge request?

**Comment by jeffschulzusc** [comment]
will do
